#!/usr/bin/env bash
# Set audio sinks before using!
# `pactl list sinks` if on pulseaudio.
# `wpctl status` if on pipewire

get_sink_number() {
  local DEVICE_NAME="$1"

  if systemctl --user is-active pipewire >/dev/null 2>&1; then
    wpctl status | awk -v target="$DEVICE_NAME" '/Sinks:/, /Sink endpoints:/ {
      if ($2 == "*") {
        if ($4 == target) print $3
      } else {
        if ($3 == target) print $2
      }
    }' | tr -d '.'
  
  elif systemctl --user is-active pulseaudio >/dev/null 2>&1; then
    pactl list sinks | awk -v dev="$DEVICE_NAME" '
      /Sink #/ { sink = substr($2, 2) }
      $0 ~ dev { print sink; exit }
    '
  else
    notify-send "No audio system detected. Please ensure PipeWire or PulseAudio is running."
    return 1
  fi
}


set_source() { \
  local SINK_NAME=$1
  if systemctl --user is-active pipewire; then
    wpctl set-default $SINK_NAME
  elif systemctl --user is-active pulseaudio; then
    pacmd set-default-sink $SINK_NAME &
  else
    notify-send "No audio system detected. Please ensure PipeWire or PulseAudio is running."
    return 1
  fi
}

enable_and_connect() {
  local B_NAME=$1
  if [ "$(bluetoothctl show | awk '/Powered/ {print $2}')" == "no" ]; then
    notify-send "Enabling Bluetooth..."
    bluetoothctl power on > /dev/null
  fi
  local DEVICE_INDEX="$(bluetoothctl devices | cut -d ' ' -f3- | grep -nFx "$B_NAME" | cut -d ':' -f1)"
  if [ -z "$DEVICE_INDEX" ]; then
    notify-send "Device not found: $B_NAME"
    return 1
  fi
  local DEVICE="$(bluetoothctl devices | head -n"$DEVICE_INDEX" | tail -n1 | cut -d ' ' -f2)"
  if bluetoothctl info "$DEVICE" | grep -q "Connected: no"; then  
    notify-send "Connecting to bluetooth device: $B_NAME"
    bluetoothctl connect $DEVICE > /dev/null
    sleep 1
  fi
}

headphones () { \
  set_source "SET SINK NAME OR DEVICE ID"
  notify-send  -h string:bgcolor:#a3be8c "Audio switched to headphones!"
}

speakers () { \
  set_source 46
  notify-send  -h string:bgcolor:#bf616a "Audio switched to speakers!"
}

bluetooth () { \
  enable_and_connect "WH-1000XM4"
  local sink_num=$(get_sink_number "WH-1000XM4")
  set_source "$sink_num"
  notify-send  -h string:bgcolor:#88c0d0 "Audio switched to bluetooth!"
}

choosespeakers() { \
  # If the script is not rendering in dmenu, remove the `-c` flag from dmenu commands.
  choice=$(printf "Headphones\\nSpeakers\\nBluetooth" | dmenu -l 3 -i -p "Choose output: ")
  case "$choice" in
    Headphones) headphones;;
    Speakers) speakers;;
    Bluetooth) bluetooth;;
  esac
}

choosespeakers
